name: Insert TOC

on:
  push:
    branches: [main]
    paths: ['README.md']

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://github.com/thegeeksam/Java-Programming/new/main/DailyConcepts -o DailyConcepts
          chmod a+x DailyConcepts
          ./DailyConcepts --insert --no-backup --hide-footer README.md
          rm DailyConcepts
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update markdown TOC
